# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-22 04:03
from __future__ import unicode_literals

import autoslug.fields
import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('000', 'Computer science, information and general works'), ('100', 'Philosophy and psychology'), ('200', 'Religion'), ('300', 'Social Sciences'), ('400', 'Language'), ('500', 'Science'), ('600', 'Technology and applied science'), ('700', 'Arts and recreation'), ('800', 'Literature'), ('900', 'History and geography')], default='000', max_length=3, verbose_name='Select Category')),
                ('is_free', models.BooleanField(default=True, verbose_name='Check to give away your book for free.')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Add a price')),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=25)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=books.models.get_photo_filename, verbose_name='Upload photos')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_photos', to='books.Book')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ('-created',),
            },
        ),
    ]
